# Generated by Django 6.0.6 on 2026-07-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('tags', models.CharField(help_text='Comma-separated tags (e.g. Django, PostgreSQL)', max_length=200)),
                ('status', models.CharField(choices=[('live', '🟢 LIVE'), ('wip', '🟡 WIP'), ('private', '🔒 Private')], default='live', max_length=20)),
                ('is_home', models.BooleanField(default=True, verbose_name='Show on Home page')),
                ('is_blog', models.BooleanField(default=True, verbose_name='Show on Blog page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
